version: '3.8'

services:
  db:
    image: postgres:14
    container_name: management-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: management-server
    restart: always
    depends_on:
      - db
      - pdf-generator
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "postgresql://user:password@db:5432/management_db"
      PDF_GENERATOR_URI: "http://pdf-generator:8080"

  pdf-generator:
    build: ./pdf-generator
    container_name: management-pdf-generator
    restart: always
    ports:
      - "8080:8080"

  client:
    build: ./client
    container_name: management-client
    restart: always
    ports:
      - "3000:80"

volumes:
  postgres_data:
